# Generated by Django 5.1.4 on 2025-01-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_review', models.BooleanField(default=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_feedback', models.TextField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('TIME_NOT_SUITABLE', 'Time Not Suitable'), ('ACCEPTED', 'Accepted'), ('FEEDBACK_PROVIDED', 'Feedback Provided'), ('   UNDER_APPROVAL', 'Under Approval'), ('  REVIEW_APPROVED', 'Review Approved'), ('  REVIEW_REJECTED', 'Review Rejected')], default='SCHEDULED', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.useraccount')),
            ],
        ),
    ]
